name: platform_user_agent
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  pigeon: ^15.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.patrikszabo.platform_user_agent
        pluginClass: PlatformUserAgentPlugin
      ios:
        pluginClass: PlatformUserAgentPlugin
      linux:
        pluginClass: PlatformUserAgentPlugin
      macos:
        pluginClass: PlatformUserAgentPlugin
      windows:
        pluginClass: PlatformUserAgentPluginCApi
      web:
        pluginClass: PlatformUserAgentWeb
        fileName: platform_user_agent_web.dart